//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeMap.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    // ApplicationSettingsBase moved to System.Configuration.ConfigurationManager package on .NET Core/.NET 5+
    // Replace with a lightweight stub so the project can build without the legacy assembly.
    internal sealed partial class Settings
    {
        // simple stub for Settings.Default used by legacy code
        private static readonly Settings defaultInstance = new Settings();

        public static Settings Default => defaultInstance;
    }
}
